global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mcp-platform'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # MCP Platform API metrics
  - job_name: 'mcp-api'
    static_configs:
      - targets: ['mcp-api:9090']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if running)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # PostgreSQL metrics (if using postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   scrape_interval: 30s

  # Nginx metrics (if using nginx-prometheus-exporter)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']
  #   scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules for common queries
# rule_files:
#   - "/etc/prometheus/rules/*.yml"
