apiVersion: v1
kind: Namespace
metadata:
  name: mcp-platform
  labels:
    name: mcp-platform
    app: mcp-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-platform-quota
  namespace: mcp-platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
